### ISSUE TITLE
Attempting to build Release BMS using Visual Studio 2019 comes up with long list of errors

### ISSUE THREAD

**Issue by DirectCrit** [YaLTeR/SourcePauseTool#105]
After following the tutorial, Visual Studio threw me a bunch of errors, almost exclusively in test.cpp.
![Screenshot 2020-01-11 03 53 52](https://user-images.githubusercontent.com/12634546/72198506-89294f00-33e3-11ea-91ee-e64576f93a70.png)

**Comment by YaLTeR** [comment]
I think you might want to stick to VS 2017 for SPT for now.

**Comment by DirectCrit** [comment]
Hmm, I'm having difficulty finding a download for VS 2017 that isn't an obvious virus or an outdated Microsoft link that auto redirects to VS 2019.
