### ISSUE TITLE
y_spt_hud commands don't work with overlay

### ISSUE THREAD

**Issue by UncraftedName** [YaLTeR/SourcePauseTool#106]
(Dec 29 2019 release)
latest build:
![out a](https://user-images.githubusercontent.com/34390438/72235361-9b8fbe00-3586-11ea-8257-b58159d83921.gif)
earlier builds:
![out](https://user-images.githubusercontent.com/34390438/72235366-a2b6cc00-3586-11ea-80f5-ef1c973231bd.gif)
binds used:
`bind , "toggle y_spt_hud_portal_bubble 1 0; toggle y_spt_hud_script_progress 1 0; toggle y_spt_hud_velocity 1 0"`
`bind . "toggle _y_spt_overlay 1 0; _y_spt_overlay_width 1000"`
(happens even if overlay doesn't overlap hud text, too lazy to remake first gif)

**Comment by Jukspa** [comment]
What's the purpose of showing different builds, arent they equally broken?

**Comment by UncraftedName** [comment]
No I'm just showing the behavior on an earlier build, just trying to make it a bit clearer as to what I expect the behavior to be like.

**Comment by Jukspa** [comment]
Alright so I didn't initially understand anything written here but adding the crosshair on the overlay wipes everything from the main screen, which was working fine prior to adding the crosshair. Don't know why or how so this is going to be broken for the foreseeable future.
