### ISSUE TITLE
Half-Life: Source Build 2707 wont allow SPT to load.

### ISSUE THREAD

**Issue by MixailTheDumbass** [YaLTeR/SourcePauseTool#108]
![Screenshot_29](https://user-images.githubusercontent.com/29043391/73344822-d3944200-42a4-11ea-8e41-decfa58a8ca0.png)
I wanted to speedrun EXACTLY HL:S, but HL:S says Frick you.

**Comment by barney-heatwave** [comment]
I don't think SPT officially supports Half-Life: Source, I can't get it to work either.
`hl1` isn't listed in the README.md so I suggest trying to use AHK for now if you want autojump

**Comment by Jukspa** [comment]
The steam version for HL:S is supported.

to 7. toukok. 2020 klo 16.58 Sabian Roberts <notifications@github.com>
kirjoitti:

**Comment by TheProJamer** [comment]
Only the second-last Steam version of Half-Life Source is supported in practice as far as I know. SPT loads in the latest update but some stuff like autojump hasn't had the relevant pattern updated so it doesn't work.

**Comment by Jukspa** [comment]
> Only the second-last Steam version of Half-Life Source is supported in practice as far as I know. SPT loads in the latest update but some stuff like autojump hasn't had the relevant pattern updated so it doesn't work.

tested with latest spt and it works
