### ISSUE TITLE
black mesa problems 

### ISSUE THREAD

**Issue by Ovuca** [YaLTeR/SourcePauseTool#11]
when i type plugin_load spt in console it says cannot load pluggin while in server (im on the main menu)

**Comment by YaLTeR** [comment]
This should work for the latest Steam BM https://yadi.sk/d/B3qbycl6gufHm

**Comment by Ovuca** [comment]
thanks testing it now

**Comment by Ovuca** [comment]
i know this is a stupid question but i like to make sure, this wont get me vac banned right? just wondering cus its a dll and it said to do -insecure for launch parameters

**Comment by mikesmiffy128** [comment]
If you do -insecure I believe you can't get VAC banned because -insecure
basically stops you from joining VAC servers.

**Comment by Ovuca** [comment]
k, also i think im doing somthing wrong because it still says the same thing

**Comment by YaLTeR** [comment]
Are you sure you renamed it? Because the one I linked is called spt-2013.dll or something

**Comment by Ovuca** [comment]
oh i need to rename it?
