### ISSUE TITLE
playing oe 2006 and getting an error

### ISSUE THREAD

**Issue by spencershoe** [YaLTeR/SourcePauseTool#121]
y_spt_pause_demo_on_tick is not available.
Speedrun hud is not available.
y_spt_motion_blur_fix has no effect.
y_spt_autojump has no effect in multiplayer.
_y_spt_afterframes has no effect.
+y_spt_duckspam has no effect.
_y_spt_setangles has no effect.
_y_spt_setpitch and _y_spt_setyaw have no effect.
_y_spt_pitchspeed and _y_spt_yawspeed have no effect.
The full game TAS solutions are not available.
_y_spt_force_90fov has no effect.
Overlay cameras have no effect.
y_spt_autojump has no effect.
y_spt_on_slide_pause_for has no effect.
as you can guess this prevents me from bhopping.
any fixes?

**Comment by Jukspa** [comment]
Are you playing a multiplayer game?

**Comment by spencerdoom12** [comment]
> 
> 
> Are you playing a multiplayer game?
no that's why i reported it, it wouldn't be an error if it was accurate

**Comment by Margen67** [comment]
What game, then? We can't read your mind.
