### ISSUE TITLE
Demo naming in tas scripts fails during map transition followed by sl

### ISSUE THREAD

**Issue by UncraftedName** [YaLTeR/SourcePauseTool#144]
Here's my sample script:
```save quick
demo you_wont_believe_what_this_script_does
playspeed 1

frames
----------|------|------|-|-|1|_y_spt_afterframes_await_load
----------|------|------|-|-|300|
sl
----------|------|------|-|-|200|
sl
----------|------|------|-|-|100|
----------|------|------|-|-|1|stop
```
The save is right before a map transition. When I run the script, I expect the following demos:
- demo from map 1
- 300 tick demo from map 2
- 200 tick demo from map 2
- 100 tick demo from map 2

What I actually get:
![image](https://user-images.githubusercontent.com/34390438/85331373-de858400-b48a-11ea-98e0-3a4099703bce.png)
- demo from map 1
- 200 tick demo from map 2
- 100 tick demo from map 2

During the first sl, there is a 300 tick demo, but it gets overwritten by the 200 tick demo.
[tas.zip](https://github.com/YaLTeR/SourcePauseTool/files/4815415/tas.zip)

**Comment by Jukspa** [comment]
if someone wants to bother fixing this, make the naming scheme for demos use dashes instead of underscores

**Comment by lipsanen** [comment]
should be fixed now
