### ISSUE TITLE
SPT not working with HL2

### ISSUE THREAD

**Issue by Puzzleous** [YaLTeR/SourcePauseTool#147]
Using the latest releases of SPT from here. I've also tried spt-2013 with HL2 with the same result. Loading the plugins produce these errors:
`] plugin_load spt`
`Loading unsigned module spt`
`Access to secure servers is disabled.`
`y_spt_pause 2 has no effect.`
`_y_spt_afterframes_reset_on_server_activate has no effect.`
`y_spt_pause_demo_on_tick is not available.`
`Speedrun hud is not available.`
`_y_spt_force_90fov has no effect.`
`Overlay cameras have no effect.`
`tas_strafe_version 1 not available`
`y_spt_disable_fade 1 not available`
`y_spt_additional_jumpboost has no effect.`
`y_spt_on_slide_pause_for has no effect.`
`tas_strafe_version 2 not available`
`HUD drawing solutions are not available.`
`SourcePauseTool version Apr 11 2020 15:55:59 was loaded in 503ms.`
`Loaded plugin "spt"`

I was able to load them before with no errors (before I tried adding -insecure to launch args), however couldn't get any of the overlays to show up at all in-game.

**Comment by Jukspa** [comment]
Looks normal, the overlay basically only works in Source Unpack due to missing patterns on other versions.
