### ISSUE TITLE
_y_spt_findangle does not exist

### ISSUE THREAD

**Issue by brododragon** [YaLTeR/SourcePauseTool#155]
I was looking through the Source Runs wiki page for SPT (https://wiki.sourceruns.org/wiki/Source_Pause_Tool) and I saw _y_spt_findangle, and tried using it in game, but it's just not there. I just redownloaded the newest SPT and am using Source Unpack.

**Comment by YaLTeR** [comment]
idk how up to date that is

**Comment by brododragon** [comment]
Is there any equivalent for current SPT?

**Comment by brododragon** [comment]
> idk how up to date that is

@YaLTeR Is there any version of it for current SPT

**Comment by YaLTeR** [comment]
@Jukspa

**Comment by Jukspa** [comment]
it's _y_spt_setangle on later versions
