### ISSUE TITLE
spt-bms not working?

### ISSUE THREAD

**Issue by kenny151345153** [YaLTeR/SourcePauseTool#159]
it just dosen't load. I did disconnect so dont ask.Does anyone have that issue?edit:I renamed the file so its easyer to type in. Ihope thats not the problem.
![螢幕擷取畫面 (108)](https://user-images.githubusercontent.com/76764692/103331187-a5fcdd80-4a9f-11eb-8de5-a719ed6926e2.png)

**Comment by Jukspa** [comment]
What version of the retail game are you on? Speedrunners are using the 0.91 beta version as far as I know. If you are having problems with this version, then I'll gotta look into it. There are some compatibility issues with plugins in 0.91 and the newer versions, so hence it's not possible to support both simultaneously in one dll.

**Comment by kenny151345153** [comment]
> What version of the retail game are you on? Speedrunners are using the 0.91 beta version as far as I know. If you are having problems with this version, then I'll gotta look into it. There are some compatibility issues with plugins in 0.91 and the newer versions, so hence it's not possible to support both simultaneously in one dll.

**Comment by kenny151345153** [comment]
how do I get the 0.91 version? I don't see it on steam

**Comment by Jukspa** [comment]
there's a version archive here: https://docs.google.com/spreadsheets/d/1It09RuaHT4jsRtivg16lHVK_x73uCvY-M8yNepzzN94/edit#gid=1985269092

**Comment by kenny151345153** [comment]
> there's a version archive here: https://docs.google.com/spreadsheets/d/1It09RuaHT4jsRtivg16lHVK_x73uCvY-M8yNepzzN94/edit#gid=1985269092

How to I use it to can't figue it out.

**Comment by thekovic** [comment]
SPT for Black Mesa is called spt-bms.dll, unless you renamed the file yourself, you should be typing "plugin_load spt-bms" into the console. I can see from the pictures that you're typing "plugin_load spt".

**Comment by mikesmiffy128** [comment]
they said they renamed it
