### ISSUE TITLE
Half Life 2 Old Engine

### ISSUE THREAD

**Issue by yes1332** [YaLTeR/SourcePauseTool#16]
How to use source pause tool with hl2oe and sdk 2006.. it's didn't works T-T

**Comment by YaLTeR** [comment]
Download spt-oe.dll, place it into `Half-Life 2\bin` folder (and **NOT** into `Half-Life 2\hl2\bin` or `Half-Life 2\hl2`), do `plugin_load spt-oe`.

**Comment by yes1332** [comment]
oh, Thx. YaLTeR!
