### ISSUE TITLE
Source Pause Tool on Black Mesa [NON-STEAM]

### ISSUE THREAD

**Issue by Bl4ckSpr4y** [YaLTeR/SourcePauseTool#17]
Hey. I'm having a problem with SPT in NON-STEAM Black Mesa. When i do "plugin_load spt" the game closes without any error messages. I know this happens with steam BM so i tried nosteam BM with RevLoader. It still doesn't work. Tried spt.dll and spt-2013.dll.

**Comment by YaLTeR** [comment]
Strange, should be working.

**Comment by BlackSpray** [comment]
It does say something after i type in plugin_load spt, but the game closes so fast, that i can't read it.

**Comment by mikesmiffy128** [comment]
Maybe try launching with `-condebug`? That might be able to create a console.log somewhere in your game folder. Just an idea.

**Comment by BlackSpray** [comment]
This is what i got:
Loading unsigned module spt
Access to secure servers is disabled.
I have `-insecure` in my flags.

**Comment by YaLTeR** [comment]
Yeah, that is normal and that means the game disables VAC. Also which Black Mesa version are you trying this on? If it's something along latest Steam then it won't work.

**Comment by BlackSpray** [comment]
I'm trying it on: Black Mesa v0.4.1 HF
