### ISSUE TITLE
problems with the "_y_spt_overlay 1" command in portal.

### ISSUE THREAD

**Issue by popb0b2** [YaLTeR/SourcePauseTool#171]
i am using the most recent version, but for some reason the "y_spt_overlay 1" command isn't working. i have turned on sv_cheats, i have the plugin on, it doesn't say a error, and i am using portal unpack. its not working. i have removed the old spt from the files, but it won't work.

**Comment by lipsanen** [comment]
the overlay only works on the source unpack
