### ISSUE TITLE
Put a MIT license on SPT

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/SourcePauseTool#185]
Let's make SPT [MIT](https://mit-license.org/)-licensed (same license as SPTLib and BXT).

I'll need an "I agree" comment from the following people:
- [x] @lipsanen 
- [x] @Margen67 
- [x] @PackSciences 
- [x] @SmileyAG 
- [x] @UncraftedName 
- [x] @InputEvelution 
- [x] @Ramalayha 
- [x] @SirWillian 
- [x] @RedHaze 
- [x] @mikesmiffy128

**Comment by mikesmiffy128** [comment]
Yep, I agree. If any of my code is still in there.

**Comment by Margen67** [comment]
I agree.

**Comment by InputEvelution** [comment]
I agree.

**Comment by SmileyAG** [comment]
Yeah I agree too.

**Comment by SirWillian** [comment]
I agree

**Comment by UncraftedName** [comment]
I agree yes

**Comment by Ramalayha** [comment]
I agree

**Comment by lipsanen** [comment]
I agree

**Comment by RedHaze** [comment]
I agree.

**Comment by PackSciences** [comment]
I agree

**Comment by YaLTeR** [comment]
Thanks everyone!
