### ISSUE TITLE
Portal 2 support

### ISSUE THREAD

**Issue by XeZrunner** [YaLTeR/SourcePauseTool#2]
Can we expect this to work with Portal 2 later on?

**Comment by Margen67** [comment]
Soon(tm)

**Comment by YaLTeR** [comment]
Portal 2 Autopause is here: https://gist.github.com/YaLTeR/d11c200eaed504177335

**Comment by Margen67** [comment]
https://github.com/YaLTeR/SourcePauseTool/pull/34

**Comment by Margen67** [comment]
Removed in 2e0c5cb3d8cfbd1b4f545bb7e154e77c14737171
