### ISSUE TITLE
SPT makes the game transparent 3 mins after loading in SPT, I'm not too sure but all that I know is it wasn't like this before.

### ISSUE THREAD

**Issue by SparklyAbs** [YaLTeR/SourcePauseTool#205]
I don't know why, but all that I know is the game become transparent 3 mins after loading in SPT. Please help me, this has been going on for 3 months. It's maybe because SPT but I'm not sure. If this is a game issue, help me with anything. If i verify the integrity of the game on steam, the game's just broken.

**Comment by lipsanen** [comment]
my game does not become transparent after 3 minutes so no idea on this one

**Comment by Reycko** [comment]
it may be a problem from your graphics driver. can you specify your gpu ?

**Comment by SparklyAbs** [comment]
Bought a new pc because of this issue :/, but thank you for your time to respond to this issue :D
