### ISSUE TITLE
Half-Life2 Ep2 (mod Offshore)

### ISSUE THREAD

**Issue by R3H4CK** [YaLTeR/SourcePauseTool#21]
Hello. Why when I do in console "plugin_load spt" game write "Could not get IServerPluginCallbacks interface from plugin "spt"Unable to load plugin "spt""?

**Comment by YaLTeR** [comment]
Try spt_2013.dll.

**Comment by R3H4CK** [comment]
Don't work I try it.

**Comment by YaLTeR** [comment]
What episode 2 are you using?

**Comment by R3H4CK** [comment]
I don't know. How to determine which version I use?

**Comment by YaLTeR** [comment]
Look in the top right while the console is open.

**Comment by R3H4CK** [comment]
There's nothing there. But I entered the "version" in the console and got it (maybe it will help):
Protocol version 11
Exe version 1.0.0.0 (ep2)
Exe build: 18:14:51 Oct  9 2007 (3258)

**Comment by R3H4CK** [comment]
Ok I found. Source Engine 11 (build 3258).

**Comment by YaLTeR** [comment]
Looks like some ancient ep2, try getting a newer one.

**Comment by R3H4CK** [comment]
Ok thx you. I'll try to find.
