### ISSUE TITLE
SPT not working in Portal 2

### ISSUE THREAD

**Issue by AngryCat415** [YaLTeR/SourcePauseTool#211]
i tried loading spt.dll but it says "Unable to load spt" but if i load spt-2013 game crashes when i load any level

**Comment by SmileyAG** [comment]
SPT support of Portal 2 been dropped while ago, needs to use SAR instead: https://github.com/p2sr/SourceAutoRecord

**Comment by lipsanen** [comment]
portal 2 is no longer supported
