### ISSUE TITLE
Game crashes upon trying to load SPT with the Ghosting mod.

### ISSUE THREAD

**Issue by Reycko** [YaLTeR/SourcePauseTool#227]
read the title, it's self explainatory.

**Comment by amogosgaming** [comment]
use the sep 18 2020 release for now, both 07-2022 and 06-2022 are broken for some reason, so yeah

**Comment by amogosgaming** [comment]
actually theres an issue with the sep 18 release too,
`y_spt_motion_blur_fix has no effect.
y_spt_autojump has no effect in multiplayer.
_y_spt_afterframes has no effect.
+y_spt_duckspam has no effect.
_y_spt_setangles has no effect.
_y_spt_setpitch and _y_spt_setyaw have no effect.
_y_spt_pitchspeed and _y_spt_yawspeed have no effect.
The full game TAS solutions are not available.
_y_spt_force_90fov has no effect.
Overlay cameras have no effect.
tas_strafe_version 1 not available
y_spt_disable_fade 1 not available
y_spt_hud_oob 1 has no effect
y_spt_autojump has no effect.
y_spt_additional_jumpboost has no effect.
_y_spt_getvel has no effect.
y_spt_on_slide_pause_for has no effect.
tas_strafe_version 2 not available
SourcePauseTool version Sep 18 2020 14:37:06 was loaded in 2396ms.`

**Comment by lipsanen** [comment]
The crash should be fixed, the warnings mentioned by amogosgaming are just a sign that some features of spt are not supported in ghosting.
