### ISSUE TITLE
HL2

### ISSUE THREAD

**Issue by FNJohn** [YaLTeR/SourcePauseTool#24]
When i put plugin_load spt in the console it says "cant find spt.dll on disk "unable to load plugin spt"
i have put it in the bin folder on HL2 the application. Also how do i put scrips into the spt such as Bhop? I have HL2 on my D drive could that be the problem?

**Comment by YaLTeR** [comment]
You put spt into the wrong folder.

**Comment by Traderain** [comment]
Also you just set y_spt_autojump to 1 to automatically jump. You don't need scripts.

**Comment by FNJohn** [comment]
Thanks for the help! I managed to figure out where to put the folder and all the commands.
