### ISSUE TITLE
old engine bug

### ISSUE THREAD

**Issue by zeroice1234** [YaLTeR/SourcePauseTool#28]
i got the source run old engine and when i type the "plugin_load spt-ne.dll" and it says: Unable to load plugin "spt.ne"
please help me with this!

**Comment by Margen67** [comment]
You need to use the spt-oe dll with OE.

**Comment by YaLTeR** [comment]
You need `spt-oe.dll`.

**Comment by zeroice1234** [comment]
hold on i will try it

**Comment by Margen67** [comment]
Make sure to put it in the right folder. (/bin not /hl2/bin etc)

**Comment by zeroice1234** [comment]
hold on

**Comment by zeroice1234** [comment]
nope it just says: 
Unable to load plugin "spt-oe.dll"

**Comment by zeroice1234** [comment]
and i did place the dll into the bin

**Comment by Margen67** [comment]
Right click the file, go to 'Properties' and click Unblock (if it's there) then Ok.

**Comment by zeroice1234** [comment]
i can open the spt.dll in the new engine but i cant open the spt-oe.dll in the old engine

**Comment by YaLTeR** [comment]
Which folder did you put it in? Give me the full path.

**Comment by zeroice1234** [comment]
i tried to put it in the sourcemods folder where i have the old engine mod for hl2. and then i tried to put the dll in the bin folder. so i have it in the dll folder

**Comment by Margen67** [comment]
If it's an OE sourcemod you need to put the spt-oe DLL in 
`C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base\bin`

**Comment by zeroice1234** [comment]
ok i will try that

**Comment by zeroice1234** [comment]
THANK YOU SO MUCH 👍 IT WORKS NOW. NOW I CAN BHOP ALL THE WAY TO VICTORY
