### ISSUE TITLE
Crashes the game upon loading

### ISSUE THREAD

**Issue by DarkblooM-SR** [YaLTeR/SourcePauseTool#285]
Self explanatory. The game instantly crashes when running the command `plugin_load spt`.

Let me now if you need any kind of log (and please tell me how to get them).

**Comment by lipsanen** [comment]
which game

**Comment by DarkblooM-SR** [comment]
Portal latest

**Comment by lipsanen** [comment]
you need spt-2013 for latest version, tested and it works

**Comment by DarkblooM-SR** [comment]
Yup, thanks
