### ISSUE TITLE
hl2 old engine auto jump not working

### ISSUE THREAD

**Issue by zeroice1234** [YaLTeR/SourcePauseTool#29]
i got finally old engine source pause tool working but it has one problem. when i typed y_spt_autojump 1. firstly it said that something is missing and then when i tried it again the bhop didnt work at all so please help me

**Comment by zeroice1234** [comment]
SOME ONE ANSWER ME PLEASE

**Comment by zeroice1234** [comment]
please just help me

**Comment by YaLTeR** [comment]
please stop spamming

**Comment by YaLTeR** [comment]
Launch the game, open the console, do `developer 1`, then `plugin_load spt-oe`, and then screenshot what it outputs and post here.

**Comment by zeroice1234** [comment]
ok hold on

**Comment by zeroice1234** [comment]
![snapshot0000](https://user-images.githubusercontent.com/30865519/29134607-b7a1f4de-7d26-11e7-80e1-6592f4261bc3.jpg)
![d1_canals_010008](https://user-images.githubusercontent.com/30865519/29134617-c231c910-7d26-11e7-94e1-00da680e7380.jpg)

**Comment by zeroice1234** [comment]
there

**Comment by zeroice1234** [comment]
is this a bug or something? im really confused

**Comment by Margen67** [comment]
You need to use +jump.

**Comment by zeroice1234** [comment]
hold on
i will try that

**Comment by zeroice1234** [comment]
i dont know the command so. can you tell me

**Comment by YaLTeR** [comment]
Go into settings, keyboard, and make sure Jump is bound to space. Then do `y_spt_autojump 1` and try holding the space bar.

**Comment by zeroice1234** [comment]
i did it and it just jump once and it didnt keep jumping (sorry for my bad english)

**Comment by zeroice1234** [comment]
and it just says. unknown command +bhop

**Comment by YaLTeR** [comment]
Another way of binding jump to space is entering `bind space +jump`

**Comment by zeroice1234** [comment]
hold on

**Comment by zeroice1234** [comment]
it does not work

**Comment by YaLTeR** [comment]
Does it still say something about +bhop?

**Comment by zeroice1234** [comment]
it does not say that and i still cant bhop

**Comment by zeroice1234** [comment]
is it a bug? im confused even more

**Comment by YaLTeR** [comment]
Might be a bug. I guess you're out of luck for now.

**Comment by zeroice1234** [comment]
do i need to reinstall the mod or what?

**Comment by zeroice1234** [comment]
can ya fix it really quick

**Comment by Centaurium** [comment]
This is something on your end, not Yalter's. Make sure you're typing plugin_load spt-oe in console, that space is bound to +jump, and that y_spt_autojump is set to 1. If you're not using the latest spt-oe.dll, you need to download it. Other than that, none of us have any trouble using SPT on the 4044 release of hl2.

**Comment by zeroice1234** [comment]
what source sdk base do you guys have?

**Comment by YaLTeR** [comment]
Other people reported that autojump does not work on OE on the latest SPT. Try SPT [v0.7-beta1](https://github.com/YaLTeR/SourcePauseTool/releases/tag/v0.7-beta1).

**Comment by zeroice1234** [comment]
i will try that

**Comment by zeroice1234** [comment]
THANK YOU SO MUCH. I CAN FINALLY BHOP. YALTER YOU ARE THE BEST PERSON I HAVE EVER SEEN

**Comment by YaLTeR** [comment]
I will keep the issue open until I fix the bug in the latest SPT.

**Comment by zeroice1234** [comment]
ok. im waiting, does it take time to fix it btw?

**Comment by YaLTeR** [comment]
Yes.

**Comment by PackSciences** [comment]
No, there is a trick called Instant Bug Fix but that's frame perfect so Yalter can't do it :/

**Comment by zeroice1234** [comment]
PackSciences. i think YaLTeR can do it. he is so good at these kind of things and all i want to do is just do tas runs

**Comment by YaLTeR** [comment]
TAS tools do not work on OE.

**Comment by zeroice1234** [comment]
k

**Comment by zeroice1234** [comment]
make them work

**Comment by YaLTeR** [comment]
No, that is too much effort.

**Comment by zeroice1234** [comment]
how do people make tas runs on old engine then?

**Comment by YaLTeR** [comment]
They don't.

**Comment by zeroice1234** [comment]
im gonna send you a link to a video.

**Comment by zeroice1234** [comment]
https://www.youtube.com/watch?v=8V5fo1VMmi8

**Comment by YaLTeR** [comment]
That's
- 1. New Engine
- 2. Done with manual scripts instead of proper TAS tools

**Comment by zeroice1234** [comment]
oh ok

**Comment by PackSciences** [comment]
![image](https://user-images.githubusercontent.com/10787214/29177172-39291772-7dee-11e7-8241-12748af8d50b.png)

**Comment by mikesmiffy128** [comment]
Yeah seriously, I don't know if you realise this, but every time you post stuff, several people potentially get sent emails, or at very least notifications. GitHub issues aren't a chat. I realise I'm not helping with this so I'll go away, but please just post messages when there's something useful to say, and not just "k" or "I'll do that."

Thanks.

**Comment by TheProJamer** [comment]
@zeroice1234 I've fixed the autojump issue in my most recent pull request. If that gets accepted before the next SPT release, you'll be able to use autojump in HL2 Old Engine.

**Comment by YaLTeR** [comment]
Oh yes we can close this now can't we
