### ISSUE TITLE
SPT commands randomly execute a frame later than intended

### ISSUE THREAD

**Issue by TheProJamer** [YaLTeR/SourcePauseTool#30]
I'm not sure what the problem is exactly, but when executing SPT commands in an afterframes script - particularly noticeable with yawspeed and pitchspeed - the game will sometimes only start executing this the frame after. This seems to happen consistently if you rerun the script, but changing the number of frames before each of the yawspeed declarations appropriately will randomly change whether this does or doesn't happen.

Game and build version: Portal, Source Engine 15 (build 5135)

**Comment by YaLTeR** [comment]
Make sure your `host_framerate` is `0.015`, also try `cl_clock_correction 0` (the CVar name might be slightly different like with `enable` in the middle or something, I don't remember), perhaps it actually makes a difference (please tell me if it does).
