### ISSUE TITLE
No valid signature found

### ISSUE THREAD

**Issue by Ubiw** [YaLTeR/SourcePauseTool#31]
Hello! I am trying to TAS on the latest ver on tf2: build label is 4082139. I tried all three versions and all of them end up with the same error:
No valid signature found for c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\spt.dll
Unable to load plugin "spt"
Thank you for making this amazing program and have a great day.

**Comment by Margen67** [comment]
To load plugins on the TF2 client you need the -insecure launch parameter.

**Comment by Ubiw** [comment]
Thank you.
