### ISSUE TITLE
plugin_load spt crashing Portal

### ISSUE THREAD

**Issue by SuperVitu64** [YaLTeR/SourcePauseTool#310]
Tried to load the .dlls, the game crashes.
I tried the spt and the spt-oe dlls but they don't seem to work
What do i do?
Version is 13.04.2022

**Comment by lipsanen** [comment]
try spt-2013, if that doesnt work post the output of the `version` command here

**Comment by SuperVitu64** [comment]
Protocol version:           24
Build Label:           7197370
Network PatchVersion:  17450

**Comment by SuperVitu64** [comment]
SPT 2013 seemed to work, thanks

**Comment by lipsanen** [comment]
nice np!
