### ISSUE TITLE
Portal 3420 crashes with spt_hud_edgebug

### ISSUE THREAD

**Issue by ez-me** [YaLTeR/SourcePauseTool#311]
I tested with Unpack and Steampipe (latest as of this issue), and they work just fine.

Steps to replicate:
1. Load spt.dll in 3420
2. enable spt_hud and spt_hud_edgebug
3. Trigger an EdgeBug

The error the game displays is the following (ignore where I have the game installed):

<details>
<summary>Runtime Error!</summary>
Microsoft Visual C++ Runtime Library

Runtime Error!

Program: G:\Portal 3420\hl2.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
</details>

Due to how it crashes, it doesn't leave a regular Source crash log.

**Comment by lipsanen** [comment]
thanks for the report, I'll try to look into this by the next release

**Comment by lipsanen** [comment]
I was too lazy but luckily evanlin did the heavy lifting
