### ISSUE TITLE
spt crashes when trying to load

### ISSUE THREAD

**Issue by JepeJete** [YaLTeR/SourcePauseTool#322]
portal 1 crashes when i try to load spt

**Comment by UncraftedName** [comment]
Please give some additional information e.g. spt & game version, where you put the spt dll, etc.

**Comment by lipsanen** [comment]
Check that you have the right version of spt for your game. If you are using the steam version use spt-2013.dll. If you are using Source Unpack or Portal 3420 use spt.dll.
