### ISSUE TITLE
spt-oe crashes on portal 3420

### ISSUE THREAD

**Issue by Maks7594** [YaLTeR/SourcePauseTool#324]
i type in plugin_load spt-oe in console and it just crashes my game, even when spt isnt loaded (cuz its literally impossible to load it)
spt-oe is in topmost bin

**Comment by Maks7594** [comment]
[hl2_3420_crash_2023_11_2T13_46_27C0.dmp](https://github.com/YaLTeR/SourcePauseTool/files/13239506/hl2_3420_crash_2023_11_2T13_46_27C0.dmp)
also this file popped up (the original extension was .mdmp)

**Comment by lipsanen** [comment]
use spt.dll
