### ISSUE TITLE
HL2 Crash while loading plugin in insecure mode

### ISSUE THREAD

**Issue by tkiepuszew** [YaLTeR/SourcePauseTool#327]
my half-life 2 is crashing when i try to load a plugin and if i type "plugin_load spt" it crashes ( plugin version: 10-2023 )

**Comment by lipsanen** [comment]
If you are using the steam version, you need spt-2013.dll
If you are using Source unpack, you need spt.dll

**Comment by lipsanen** [comment]
works on my machine tm
