### ISSUE TITLE
Half life 2 old engine problems

### ISSUE THREAD

**Issue by ResonateBob** [YaLTeR/SourcePauseTool#33]
When ever i load in the pause tool plugin i get an error that says Unable to load plugin "spt". i put the plugin in the right place and the right file, i don't see the problem. I would like a solution, thanks.

**Comment by YaLTeR** [comment]
Make sure you put the plugin in the right place since for oe it is the topmost `bin` folder. Also make sure you renamed it from spt-oe.dll to spt.dll.

**Comment by ResonateBob** [comment]
oh okay, thank you very much. My problem was i didnt rename it.
.

**Comment by YaLTeR** [comment]
Oops, didn't read the last sentence properly.

**Comment by YaLTeR** [comment]
Can you write the full path to where you put `spt.dll`?

**Comment by ResonateBob** [comment]
Sure, it's C:\Program Files (x86)\Steam\steamapps\sourcemods\hl2oe\bin that's where i put the spt.dll.

**Comment by YaLTeR** [comment]
It should go into the Source SDK 2006's bin folder, not the OE sourcemod.

**Comment by ResonateBob** [comment]
Oh okay thanks a lot Yalter!
