### ISSUE TITLE
Major Crashes with SPT-2013 plugin on.

### ISSUE THREAD

**Issue by hellomynameisapistol** [YaLTeR/SourcePauseTool#335]
Route kanals. every outside thing/ third metrocop with a gun.
airboat section. when you punt the barrel to release the supply crate. the game crashes.
another airboat section crash. this time the helicopter boss is making the crash.
another one in black mesa east. when you see the scanners. you have time before the crash (its inevitable)

I'll probably update this list more. play the game with the plugin on and try to find every crash. document it here, in the comments.

**Comment by Nacroni** [comment]
I think Portal also gets a similar crash when I tried to load it in.

**Comment by Nacroni** [comment]
Yeah, was playtesting and the April 2024 version _does_ crash at the beginning of Route Kanal (where you see the Metrocop up on of a flight of stairs, where you can clearly see the Citadel), weirdly doesn't seem to crash on the December 2023 version.

**Comment by viktorvesely** [comment]
Both the April (2024) and the December (2023) version crash for me in the route canal where you can see the cop on the stairs
