### ISSUE TITLE
Not working in Portal 1(Source Unpack)

### ISSUE THREAD

**Issue by Zorro-no** [YaLTeR/SourcePauseTool#336]
It says that there is no such command and none of the commands actually work
![image](https://github.com/YaLTeR/SourcePauseTool/assets/108409246/c5174dfe-15f1-4c9e-b400-242d5055e9db)

**Comment by evanlin96069** [comment]
From what I’ve seen in your screenshot, `config.cfg` ran the spt commands before spt loaded, so the game  said unknown commands. Can you try just typing some spt commands in the console to see if it works? (Note: some spt cvars require `sv_cheats 1` or being connected in a single player server to change it.)

For why there will be spt commands in `config.cfg`, usually cvar with FCVAR_ARCHIVE flag will get recorded in `config.cfg` and executed automatically before `autoexec.cfg`. If you load spt in the `autoexec.cfg`, it’ll be too late. The intended way is to load the plugin using .vdf file in the addons folder, but unfortunately,  spt has trouble loading in such early state when the game is not fully booted. The current recommended way will be loading spt in `autoexec.cfg` and then config the spt cvars after that.

**Comment by Zorro-no** [comment]
Ok, so the plugin works, I just wasn't loaded into a game. I only edited the autoexec.cfg to have "plugin_load spt", so I guess the cvars got saved and are trying to be used without them existing yet.

**Comment by lipsanen** [comment]
spt and sst also don't really work together, so I would not recommend using them at the same time.
