### ISSUE TITLE
Game freezes upon reload (3420).

### ISSUE THREAD

**Issue by ADiamondChanger** [YaLTeR/SourcePauseTool#347]
When I open the game up from a minimized point, it freezes.

**Comment by lipsanen** [comment]
Hey I found a fix for a crash in 3420 but I'm unsure if it's your problem. Could you grab the spt.dll from here and test if it was fixed?
https://github.com/YaLTeR/SourcePauseTool/actions/runs/10946646455/artifacts/1954707838
