### ISSUE TITLE
Portal sometimes crashes when going through a portal fast with autojump enabled

### ISSUE THREAD

**Issue by sabianroberts** [YaLTeR/SourcePauseTool#36]
Every time I go through a portal fast with autojump enabled, the game closes/crashes.

**Comment by YaLTeR** [comment]
That's really strange. Have you tried w/o autojump? Without SPT? Do you have a save right before a crash?

**Comment by DiseCoding-or-DiseGames** [comment]
I haven't tried without autojump. I've tried without SPT, and it never crashes.

**Comment by YaLTeR** [comment]
Then why did you specify you had autojump enabled? It's the least likely cause.

**Comment by PackSciences** [comment]
No video.
No correct description.
You could at least put some effort to give Yalter enough clues to solve your problem.
"fast" is not precise.
You didn't mention what cvar you had on and which ones are off.
You imply that autojump is the cause while it's the least likely.
If I was Yalter, I would probably have thrown my computer out of my window.

**Comment by YaLTeR** [comment]
Calm down Pack. I need your game version, SPT version, any changes you made to SPT settings and a save right before a crash occurs (so, like, save of you flying into a portal, such that when you load it and don't press anything the game crashes).

**Comment by DiseCoding-or-DiseGames** [comment]
It doesn't happen without autojump. Sorry for the inconvenience.

**Comment by DiseCoding-or-DiseGames** [comment]
I am using the latest SPT version, and I'm using Source Engine 24 (build 1910503).
SPT Commands I used:
y_spt_autojump 1
y_spt_pause 0
I do not know how to give you a specific game save.

**Comment by YaLTeR** [comment]
Type `save crash` to save, then upload `crash.sav` from the `portal\save\` folder.

**Comment by DiseCoding-or-DiseGames** [comment]
ok

**Comment by DiseCoding-or-DiseGames** [comment]
Here it is: https://drive.google.com/file/d/0B7VE7MUPXIdKMk1veHc5Q0FyTnc/view?usp=sharing

**Comment by Margen67** [comment]
@DiseCoding-or-DiseGames 👀
