### ISSUE TITLE
any way to make it work in linux?

### ISSUE THREAD

**Issue by wave98** [YaLTeR/SourcePauseTool#44]
stupid question considering the files are dlls, but can it be compiled for linux, or something?

**Comment by YaLTeR** [comment]
It can but it won't work because hooking on Linux and Windows is completely different and there's no Linux hooking support in SPT.

**Comment by wave98** [comment]
ah, alright. any other way i could get similar features that spt offers but for linux?

**Comment by YaLTeR** [comment]
Not really, I don't know of any plugin that does the same stuff. You see, pretty much no one makes Source runs on Linux so there wasn't any demand. You could run the Windows games under wine with SPT.

**Comment by wave98** [comment]
@YaLTeR if i need certain features, i guess i'll need wine. but for now, i can just use a macro program for autohop.

**Comment by Margen67** [comment]
@wave98 Something that spams keys like AHK won't be nearly as accurate as SPT.

**Comment by wave98** [comment]
@Margen67 of course not, but it's the best i can get.
