### ISSUE TITLE
plugin_load spt-oe doesn't work

### ISSUE THREAD

**Issue by OpaOpaOpapa** [YaLTeR/SourcePauseTool#45]
plugin_load spt-oe doesn't work
![image](https://user-images.githubusercontent.com/34745462/38550953-532bbe02-3cd1-11e8-982b-817ffe840d7c.png)

**Comment by OpaOpaOpapa** [comment]
On Old Engine

**Comment by YaLTeR** [comment]
It's not that `plugin_load spt-oe` doesn't work it's that your engine has no `plugin_load` command as it says right there in the console, it's probably super ancient.

**Comment by OpaOpaOpapa** [comment]
How to inject spt-oe

**Comment by YaLTeR** [comment]
Which version does it say in the top right corner?

**Comment by OpaOpaOpapa** [comment]
Build 2187

**Comment by TheProJamer** [comment]
That version of Half-Life 2 is probably too old to support plugin loading. If you want to use SourcePauseTool with Half-Life 2 Old Engine, download build 4044 here: https://mega.nz/#!Sp1VUIhL!4SMOMV0WOaWwcK8HuT4evSXFverrw-ROuzf0bCpFnEs

Put the hl2oe folder in the sourcemods folder in your Steam directory, and put spt-oe in the bin folder of Source SDK Base 2006 (must be downloaded for the mod to work also). If you do all this correctly, you should be able to load SPT. If you wish to specifically use a version of HL2 which doesn't have save delete + other Source Engine 2004 specific traits, I can give you a link to the 2707 build, although the 4044 build is much more strongly recommended.

**Comment by OpaOpaOpapa** [comment]
I need Forward Hopping

**Comment by TheProJamer** [comment]
Forward bhop is possible in version 4044, it was only after that when the bulk of Half-Life 2 glitches were patched or severely limited in usability.

**Comment by OpaOpaOpapa** [comment]
Give 2707 link please

**Comment by TheProJamer** [comment]
The only real difference in practice between speedrunning Half-Life 2 on Source 2004 and 2006 is that 2006 builds (like 4044) allow for the extra glitch of save deletion, and that 4044 is the more commonly accepted build to run on. Builds like 2187 and 2707 are just as usable, but it's disadvantageous in a few ways to use that. Nonetheless, here is the 2707 build link if you really need it for some reason:
https://drive.google.com/open?id=0BwUxWsGVqy5DNUtUZmI1RXBWa0k

For this, you simply need to extract the contents of the ISO with something like 7zip, and put spt-oe.dll in the bin folder.

**Comment by OpaOpaOpapa** [comment]
Thanks
