### ISSUE TITLE
unable to load spt

### ISSUE THREAD

**Issue by Lysithea-ciel** [YaLTeR/SourcePauseTool#46]
when I enter "plugin_load spt", the console returns this:
Loading unsigned module spt
Access to secure servers is disabled.
Unable to load plugin "spt"
Unable to load plugin "spt"

I've tried putting spt.dll in both /common/Half-Life 2/hl2/ and /common/Half-Life 2/ and restarting the game each time. I'm using new engine and launching with -insecure.

**Comment by TheProJamer** [comment]
Alright, there's a few things that you need clearing up on:
- The alternative location for the DLL is not common/Half-Life 2, but common/Half-Life 2/bin. This is worth noting if you plan on using SPT with older versions of Source.
- From the looks of things, you're trying to use SPT with Steampipe Half-Life 2. For this, you want to use spt-2013.dll instead.
- To further explain the previous point, although "new engine" is a common buzzword for SE 2007, 2009 and 2013/Steampipe, these are all different engines that function differently and so it's easier to specify exactly what you're using. Again, if you're just running a plain Steam installation of Half-Life 2, use spt-2013.dll. If you're using older versions of Source which still feature glitches like ABH, then use spt.dll. If you're using even older versions of Source (such as SE 2004 and 2006), use spt-oe.dll. Finally, if you're running Portal 2, use spt-p2.dll.

Hope this solves the issue and clears you up on some details.

**Comment by mikesmiffy128** [comment]
Maybe I'm wrong but surely if it says it's an unsigned module that would mean it hasn't outright failed to find the file? That said I can't think of any other reason all 3 would fail to load other than putting them in the wrong place, so that's pretty weird...

**Comment by YaLTeR** [comment]
Maybe the latest steam HL2 switched to a newer version of the interfaces which would prevent SPT from loading.

**Comment by TheProJamer** [comment]
Try loading spt-2013.dll in the Half-Life 2/hl2 directory. To my knowledge, that's the only place that Source 2013 will check for DLLs in the latest release, and you seem to have only indicated attempting to load it with it in the Half-Life 2/bin directory.
