### ISSUE TITLE
Don't working in HL1S

### ISSUE THREAD

**Issue by OpaOpaOpapa** [YaLTeR/SourcePauseTool#47]
I can't inject spt with plugin_load spt.
![image](https://user-images.githubusercontent.com/34745462/39994287-43ac5f00-5792-11e8-8b5e-c3c382f40337.png). If you can, then give a link to HL1S v2187 please.

**Comment by actionstorm** [comment]
Put spt.dll into your steamapps/common/Half-Life 2/hl1 folder.

**Comment by TheProJamer** [comment]
Please tell me what build of Half-Life Source you're using. If you're just using Steam, then you should be using spt-2013.dll, put it in the directory actionstorm suggested, and of course use plugin_load spt-2013 instead.
