### ISSUE TITLE
Portal 1 not loading the plugin

### ISSUE THREAD

**Issue by MrMeeseesks** [YaLTeR/SourcePauseTool#49]
When I launch Portal 1, it doesn't let me load in the plugin. It says that it couldn't be found, yet the plugin's DLL is in the Portal 1 directory.

**Comment by YaLTeR** [comment]
It should be in the `portal` folder that is inside the main Portal folder.

чт, 26 июля 2018 г., 16:21 Mason Garrin <notifications@github.com>:
