### ISSUE TITLE
Plugin_load in Old Engine

### ISSUE THREAD

**Issue by MrVybson** [YaLTeR/SourcePauseTool#51]
I'm playing on BitRain's 2004 version and it seems that that version just doesn't know the command to load the spt. I tried developer 1, sv_cheats 1, insecure mode, but the command isn't working. So does that mean I have to get a newer version of the game for the tool to work?

**Comment by Traderain** [comment]
You have to use an injector if remember correctly

**Comment by YaLTeR** [comment]
SPT won't work with an injector. It needs `plugin_load`. I guess it's not supported on really old builds. I'll try to get someone familiar with those to clarify.

**Comment by TheProJamer** [comment]
I'm guessing you're using build 2187. That doesn't have plugin_load. My recommendation is that you use build 2707, in which everything should work correctly.
