### ISSUE TITLE
Portal 1 wont load spt

### ISSUE THREAD

**Issue by Nilsber** [YaLTeR/SourcePauseTool#54]
Portal 1 wont load spt, the console output is 

Could not get IServerPluginCallbacks interface from plugin "spt"Unable to load plugin "spt"

Any fix? The spt.dll and spt-2013.dll are both in bin file

**Comment by YaLTeR** [comment]
Could you attach a screenshot of the version text in a top corner of the screen when the console is open?

**Comment by Nilsber** [comment]
> Could you attach a screenshot of the version text in a top corner of the screen when the console is open?

![image](https://user-images.githubusercontent.com/44580693/47663791-5e6c2580-dba6-11e8-97a9-19a3977ac2e3.png)

**Comment by YaLTeR** [comment]
Read my message again pls

**Comment by PackSciences** [comment]
What Yalter said is "could you please show the info related to the game version". This information is located in the top corner; he has not been asking you the version of SPT.

**Comment by Nilsber** [comment]
> Read my message again pls

Source Engine 11 (build 3258) Map 'background1'

**Comment by TheProJamer** [comment]
SPT does not work on early versions of Source 2007 yet. Unless there is a reason you must use build 3258 in particular, you are better off downloading the Source Unpack and using that instead.

**Comment by Nilsber** [comment]
> SPT does not work on early versions of Source 2007 yet. Unless there is a reason you must use build 3258 in particular, you are better off downloading the Source Unpack and using that instead.

basically how do i get the correct one because i even had no source thing yet and still didnt work in that way

**Comment by Nilsber** [comment]
hello? still alive?

**Comment by YaLTeR** [comment]
You will probably want Portal from the [Source Unpack](https://wiki.sourceruns.org/wiki/Source_Unpack).
