### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CrystVEVO** [YaLTeR/SourcePauseTool#59]
yo i was wondering if this helps the loading time between maps on hl1 just wondering cuz the gaps make it pretty hard to maintain a rythm when speedrunning

**Comment by PackSciences** [comment]
1. SPT does NOT work on HL1
2. SPT does NOT "help" the loading time between maps

**Comment by CrystVEVO** [comment]
Okay thanks for the reply, do you know of anything that could fix the lost time?

**Comment by YaLTeR** [comment]
Sorry, but this is not the correct place to discuss general questions. This has nothing to do with SPT. Please use #source or #goldsrc on https://discord.gg/sourceruns for general questions about the games and their speedrunning.
