### ISSUE TITLE
is _y_spt_overlay not supported in hl2 new engine?

### ISSUE THREAD

**Issue by floawb** [YaLTeR/SourcePauseTool#60]
I have been trying to use the "rearview mirror" for abh but nothing happens when I change the cvars.

**Comment by YaLTeR** [comment]
cc @Jukspa

**Comment by Jukspa** [comment]
What version of the game are you using @jackman-chan? Current steam version or source unpack?

**Comment by jackman-chan** [comment]
ok i totally forgot to answer this, but I have the current steam version... Thats probably the issue i guess

**Comment by jlipsanen** [comment]
yeah I dont think Steam version is supported atm but I might be able to look into it at some point

**Comment by Jukspa** [comment]
yeah Steam version isn't supported atm, but I might be able to look into it at some point
