### ISSUE TITLE
Half Life 2 isnt detecting spt 2013 

### ISSUE THREAD

**Issue by Whatamadoo** [YaLTeR/SourcePauseTool#65]
The console says:
] plugin_load spt-2013
Loading unsigned module spt-2013
Access to secure servers is disabled.
Unable to load plugin "spt-2013"
Unable to load plugin "spt-2013"

im using the steam version of hl2 and ive tried: common\Half-Life 2, common\Half-Life 2\hl2, common\Half-Life 2\hl2\bin

**Comment by Jukspa** [comment]
Can you post a screenshot of the contents in your hl2 folder with the spt 2013 dll inside it?

**Comment by Whatamadoo** [comment]
![image](https://user-images.githubusercontent.com/51574957/59217627-36e52e80-8b73-11e9-998e-69627023a915.png)
the custom folder has nothing in it btw.

**Comment by Whatamadoo** [comment]
fixed it by shoving spt-2013 in common/half-life 2, common/half-life 2/hl2 and common/half-life 2/bin. and told steam to update the steam cloud files with spt. dont know which one worked but it did
