### ISSUE TITLE
Black Mesa

### ISSUE THREAD

**Issue by Jung504** [YaLTeR/SourcePauseTool#67]
I'm running the sourcemod version, launching with -insecure.   spt loads but as soon as +jump is sent the game crashes.   

y_spt_autojump has no effect in multiplayer.
_y_spt_setangles has no effect.
_y_spt_setpitch and _y_spt_setyaw have no effect.
_y_spt_pitchspeed and _y_spt_yawspeed have no effect.
The full game TAS solutions are not available.
_y_spt_force_90fov has no effect.
Overlay cameras have no effect.
y_spt_on_slide_pause_for has no effect.
SourcePauseTool version May 12 2019 21:21:42 was loaded in 1251ms.
Loaded plugin "spt"

**Comment by Jukspa** [comment]
You dont need to launch with -insecure, you can load any plugins in single player. Dunno if that's causing the game think it's in multiplayer or something.

**Comment by Jung504** [comment]
Same issue either way... I was initially trying it without.    The plugin loads and pauses the initial save like it should but as soon as I jump the game closes without any errors.

**Comment by Jukspa** [comment]
Hmm ok. Have you tried older versions of spt? Maybe some recent update broke it.

**Comment by YaLTeR** [comment]
So... did you find a version that works? Which one?

**Comment by Jukspa** [comment]
Can reopen this imo, I'll try to look into it since I probably broke the mod version compability in a recent version.

**Comment by Jukspa** [comment]
Should be fixed in #69
