### ISSUE TITLE
Error: No effect!

### ISSUE THREAD

**Issue by Traderain** [YaLTeR/SourcePauseTool#7]
It gives this on clean install. It works but i wanted to remind you.
Console log:

SPT: y_spt_motion_blur_fix has no effect.
SPT: _y_spt_afterframes has no effect.
SPT: +y_spt_duckspam has no effect.
SPT: _y_spt_setpitch and _y_spt_setyaw have no effect.
SPT: _y_spt_pitchspeed and _y_spt_yawspeed have no effect.
SPT: y_spt_autojump has no effect.
SPT: y_spt_additional_abh has no effect.
SPT: _y_spt_getvel has no effect.

**Comment by YaLTeR** [comment]
This means that SPT could not find places in memory required for those functions to work. This generally happens with mods with custom DLLs because there are no patterns in SPT for them.

**Comment by brownspike** [comment]
I've been receiving similar errors on a clean install of Portal.  

] plugin_load spt
SPT: y_spt_motion_blur_fix has no effect.
SPT: y_spt_autojump has no effect.
SPT: y_spt_additional_abh has no effect.
SourcePauseTool v0.7-beta was loaded in 169ms.
Loaded plugin "spt"

The y_spt_autojump command doesn't work ingame.  I was able to get it working in Half Life 2, but not Portal.

**Comment by YaLTeR** [comment]
They changed something in the latest Portal and no one plays it anyway so I didn't really bother updating the patterns.

**Comment by YaLTeR** [comment]
If you need it PM me somewhere and I'll update them.

**Comment by Traderain** [comment]
Thanks, but I closed it because it has been answered and I don't need it anymore.
