### ISSUE TITLE
Rearview mirror only faces 1 way (HL2 Source Unpack)

### ISSUE THREAD

**Issue by Zohondekids** [YaLTeR/SourcePauseTool#71]
So I've updated my source unpack's SPTs to the latest (May 12, 2019), and it loads correctly ingame. The commands work except the overlay only faces in one direction (and yes, I set overlay type to 2). I'd also like to add that the rearview mirror works fine in portal (also running on the source unpack version using the same SPT dll I used for HL2)
![hl2_2019-07-22_20-04-51](https://user-images.githubusercontent.com/39644689/61675072-5e73fe80-acbc-11e9-9914-0c755346f1a5.jpg)
![hl2_2019-07-22_20-10-23](https://user-images.githubusercontent.com/39644689/61675161-cc202a80-acbc-11e9-8495-7884c5e5ca51.jpg)
![hl2_2019-07-22_20-10-30](https://user-images.githubusercontent.com/39644689/61675167-cf1b1b00-acbc-11e9-8cfd-707a288296d6.jpg)
![hl2_2019-07-22_20-10-40](https://user-images.githubusercontent.com/39644689/61675169-d17d7500-acbc-11e9-880f-20564066c55e.jpg)
![hl2_2019-07-22_20-06-55](https://user-images.githubusercontent.com/39644689/61675074-60d65880-acbc-11e9-9628-36e855daf501.jpg)
![hl2_2019-07-22_20-09-13](https://user-images.githubusercontent.com/39644689/61675115-98450500-acbc-11e9-9585-1bae11cfd84c.jpg)

**Comment by YaLTeR** [comment]
@Jukspa

**Comment by Jukspa** [comment]
Oh woops, I'll look into this in a bit
