### ISSUE TITLE
May 12 2019 Release crashes game when loaded via vdf

### ISSUE THREAD

**Issue by Margen67** [YaLTeR/SourcePauseTool#74]
* Put `spt.dll` in mod folder (hl2)
* Make a new folder named `addons` and create a file called `spt.vdf` with the following contents:
```
"Plugin"
{
	"file"	"spt"
}
```
* *crash*

This works fine with the [Dec 11 2018 release](https://github.com/YaLTeR/SourcePauseTool/releases/tag/dec-11-2018).

**Comment by lipsanen** [comment]
think these got fixed, vdf support is still a little scuffed though
