### ISSUE TITLE
[suggestion] add crosshair on overlay

### ISSUE THREAD

**Issue by sirtomato999** [YaLTeR/SourcePauseTool#78]
it would be really nice to have a cvar or something that added a crosshair on the overlay so you can make precise portal shots

**Comment by Jukspa** [comment]
This is true but the way to hud drawing works is very mysterious and my earlier attempts and drawing stuff on the overlay resulted in the main screen hud getting wiped

**Comment by sirtomato999** [comment]
oh ok
