### ISSUE TITLE
SPT wont show the hud.

### ISSUE THREAD

**Issue by Ogar-the-best** [YaLTeR/SourcePauseTool#83]
I tried to enable disable the hud and it didnt work. 
HL2 version: Source Engine 24 (build 2257546)

**Comment by Jukspa** [comment]
overlay only works on source unpack for the time being

**Comment by Ogar-the-best** [comment]
Oh. The Source Unpack is what version? I think its 2184 or 4044.

**Comment by Ogar-the-best** [comment]
Also, I would know, is there a link to the source unpack **NOT** on mega? Because mega always gives the message (Your quota for downloading on Mega has ended.) and then its like (BUY MEGA PRO YOU POOR SHIT). I really need a link to an mediafire download.

**Comment by Ogar-the-best** [comment]
Nvm. I got it installed.
