### ISSUE TITLE
No overlay command.

### ISSUE THREAD

**Issue by MixailTheDumbass** [YaLTeR/SourcePauseTool#84]
Im using the Source Unpack and theres no "_y_spt_overlay" or "y_spt_hud_(something)" command.

Build 5135 Nov28 2012 Source 15.

**Comment by mikesmiffy128** [comment]
Make sure you're not running an old SPT version:
* Search inside the unpack installation for spt.dll, there will be several redundant copies. Delete them all.
* Get latest SPT from here an put it under hl2/ (all games / mods will pick this up)

**Comment by Jukspa** [comment]
works fine for me

**Comment by Ogar-the-best** [comment]
I forgot to answer, but with the new SPT dll the problem still persists.

**Comment by Jukspa** [comment]
the command is _y_spt_overlay

**Comment by Jukspa** [comment]
if that is not the issue, type

```
plugin_load spt
version
_y_spt_overlay
```
into console and post the console output here

**Comment by Loxby** [comment]
![grafik](https://user-images.githubusercontent.com/33966128/71471363-903f4300-27cf-11ea-8b0b-af6bb7ca469a.png)
Hey, I got the same problem. Is this the right version? If so, what should I do?

**Comment by Margen67** [comment]
That version is ancient. Get a newer version: https://github.com/YaLTeR/SourcePauseTool/releases/latest

**Comment by mikesmiffy128** [comment]
@Wanimus see my very first reply to this issue, you probably have redundant versions of SPT that come with Unpack
