### ISSUE TITLE
Crash on jump (Half-Life 2) 

### ISSUE THREAD

**Issue by Gnerus** [YaLTeR/SourcePauseTool#85]
So after the latest _HL2_ patch, my game crashes whenever I press space. 
That only happens with SPT installed, though. So I think that could be the issue. 
The only changes I've done is turn **y_spt_pause to 0.**
**Game BuildID: 4233294 
SPT Version is the latest build (Aug 23 2019)**

**Comment by Peter498199** [comment]
Here's a fix:  Go to your library, right click Half-life 2, click Properties, click on Betas and then select the "previous" beta which is the one before the patch. And then it's fixed.

**Comment by Gnerus** [comment]
Can't do that, you need a Beta access code to opt into Betas. And if you didn't mean Private Betas, then still I can't opt into any Beta program, it's greyed out, can't click it.

**Comment by Peter498199** [comment]
It should be normally there. It's in the same menu as the public beta
![s](https://user-images.githubusercontent.com/55914528/65815317-46ee5000-e1ee-11e9-8ae0-c8e328dfa45a.PNG)

**Comment by Gnerus** [comment]
Well, funny thing is, after a Steam update, it works now. I can select the option in the screenshot. Thanks for the help! And sorry for wasting your time lol.
