### ISSUE TITLE
Instant crash, source unpack won't work either.

### ISSUE THREAD

**Issue by RelXen** [YaLTeR/SourcePauseTool#88]
Crashes as soon as I try to jump after loading. spt, nor spt-2013 work, and source unpack won't launch the game via the .bat files at all and has limited functionality when launched directly via hl2 exe

**Comment by Jukspa** [comment]
What version of the game is this on?

**Comment by Jukspa** [comment]
latest hl2 update broke spt, source unpack still works

**Comment by RelXen** [comment]
Huh, weird. Source unpack simply won't launch for me via the batch files (even in admin mode), launching via the .exe and loading source unpack's spt works.. but the commands are very limited, any idea why that could be? I couldn't find any solution.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
