### ISSUE TITLE
[Request] Add support for recording demos through s/l

### ISSUE THREAD

**Issue by UncraftedName** [YaLTeR/SourcePauseTool#91]
Currently there is no easy way to record demos through save-loads in a single script. It seems that the current recording mechanism is just using the record command, which stops as soon as you save-load. The only way to go recording demos like this atm is by using speedrun_segment which doesn't keep the same demo name as at the top of the script, or by doing some janky jankyness with y_spt_pause 2.

**Comment by Jukspa** [comment]
Just to clarify, the suggestion is to automate the recording of the second demo after the save/load has completed.
