### ISSUE TITLE
y_spt_hud_oob crashes game during demo playback

### ISSUE THREAD

**Issue by UncraftedName** [YaLTeR/SourcePauseTool#92]
Using the Aug 23 build

**Comment by Jukspa** [comment]
yea this is unforunately the case. it would require a complete overhaul as to how it's calculated to fix this

**Comment by Jukspa** [comment]
looks fixed as bill said, not entirely sure what did it but there you go

**Comment by SirWillian** [comment]
The problem before was that GetPlayerEyePos would calculate the eye position using the server-side player, which causes problems when replaying demos, while now the camera position (that shows on cl_showpos) is being used
