### ISSUE TITLE
Nov 16 release breaks vertical movement in the sg overlay

### ISSUE THREAD

**Issue by UncraftedName** [YaLTeR/SourcePauseTool#95]
Older versions:
![_old gif](https://user-images.githubusercontent.com/34390438/69468161-00c1f280-0d40-11ea-8559-370c29bdf943.gif)
Nov 16 release:
![_new gif](https://user-images.githubusercontent.com/34390438/69468181-0fa8a500-0d40-11ea-993c-2b9c8a94a0a0.gif)

**Comment by Jukspa** [comment]
oops
